[workspace]
members = [
    "bcfs",
    "blockchain-traits",
    "examples/ballot",
    "examples/erc20",
    "examples/hello-world",
    "examples/messaging",
    "examples/sealed-auctions",
    "memchain",
    "oasis",
    "oasis-build",
    "oasis-macros",
    "oasis-rpc",
    "oasis-test",
    "oasis-types",
]
exclude = ["tests"]

[profile.release]
incremental = false
lto = true
opt-level = 3
