[workspace]
members = [
    "bcfs",
    "blockchain-traits",
    "idl-gen",
    "mantle",
    "mantle-macros",
    "mantle-test",
    "mantle-types",
    "memchain",
]
exclude = ["examples", "tests"]

[profile.release]
incremental = false
lto = true
opt-level = 3
