[workspace]
members = [
    "bcfs",
    "idl-gen",
    "memchain",
    "oasis-std",
    "oasis-macros",
    "oasis-test",
    "oasis-types",
]
exclude = ["tests"]


[profile.release]
incremental = false
lto = true
opt-level = 3
