[workspace]
members = [
    "bcfs",
    "blockchain-traits",
    "examples/ballot",
    "examples/erc20",
    "examples/hello-world",
    "examples/messaging",
    "examples/sealed-auctions",
    "mantle",
    "mantle-build",
    "mantle-macros",
    "mantle-rpc",
    "mantle-test",
    "mantle-types",
    "memchain",
]
exclude = ["tests"]

[profile.release]
incremental = false
lto = true
opt-level = 3
