version: 2.1


executors:
  rust:
    environment:
      PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
    docker:
      - image: oasislabs/rust:latest
    resource_class: xlarge

  rust_pending:
    environment:
      PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
    docker:
      - image: oasislabs/rust:pending
    resource_class: xlarge

  docker_builder:
    environment:
      IMAGE_NAME: oasislabs/rust
    docker:
      - image: circleci/buildpack-deps:bionic


commands:
  cache_oasis_build:
    steps:
      - checksum_oasis_build
      - save_cache:
          key: oasis-build-{{ checksum "oasis-build.sums" }}
          paths:
            - ~/.cargo/bin/oasis-build

  restore_oasis_build:
    steps:
      - checksum_oasis_build
      - restore_cache:
          keys:
            - oasis-build-{{ checksum "oasis-build.sums" }}

  checksum_oasis_build:
    steps:
      - run:
          name: Checksum oasis-build
          command: |
            find oasis-build/src -type f -name "*.rs" | \
              sort | xargs md5sum oasis-build/Cargo.toml > oasis-build.sums
            echo $(rustc --version) >> oasis-build.sums

  update_toolstate:
    steps:
      - checkout
      - run:
          name: Install oasis-build
          command: |
            cargo build --release -p oasis-build && cp target/release/oasis-build ~/.cargo/bin
      - run:
          name: Package oasis-build for rustup
          command: |
            bin_dir=oasis-build/oasis-build/bin
            mkdir -p $bin_dir
            cp target/release/oasis-build $bin_dir
            echo 'oasis-build' > oasis-build/components
            echo $(git rev-parse HEAD) > oasis-build/version
            echo '3' > oasis-build/rust-installer-version
            echo 'file:bin/oasis-build' > oasis-build/oasis-build/manifest.in
            tar czf oasis-build.tar.gz oasis-build
      - run:
          name: Push to S3 bucket
          command: |
            rustc_version=$(rustc --version | cut -d'(' -f 2 | cut -d')' -f 1 | tr ' ' '_')
            llvm_target=$(rustc --print sysroot | cut -d'-' -f2-)
            aws s3 cp oasis-build.tar.gz s3://oasis-framework/$rustc_version/$llvm_target/oasis-build.tar.gz

  docker_push:
    parameters:
      tag:
        type: string
    steps:
      - run:
          name: Push to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push oasislabs/rust:<< parameters.tag >>


jobs:
  init:
    executor: rust
    steps:
      - checkout
      - run:
          name: Rustfmt
          command: cargo fmt -- --check
      - restore_oasis_build
      - run:
          name: Build oasis-build
          command: |
            which oasis-build || \
              (cargo build -p oasis-build && cp target/debug/oasis-build ~/.cargo/bin)
      - cache_oasis_build
      - run:
          name: Unit test
          command: cargo test

  clippy:
    executor: rust
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Clippy
          command: |
            rustup component add clippy || exit 0
            cargo clippy --all-features -- -D clippy::all

  wasm_build:
    executor: rust
    steps:
      - checkout
      - run:
          name: Wasm build
          command: cargo build --target wasm32-unknown-unknown --all-features -p memchain -p bcfs

  build_standalone_examples:
    executor: rust
    environment:
      RUSTC_WRAPPER: oasis-build
    steps:
      - checkout
      - restore_oasis_build
      - run:
          name: cargo build
          command: |
            RUSTC_WRAPPER=oasis-build cargo build --target=wasm32-wasi \
              -p ballot \
              -p erc20 \
              -p hello-world \
              -p messaging \
              -p sealed-auctions

  test_idl:
    executor: rust
    environment:
      RUSTC_WRAPPER: oasis-build
    steps:
      - checkout
      - restore_oasis_build
      - run:
          name: Test IDL generation
          working_directory: tests/idl-gen
          command: cargo build --target wasm32-wasi --bins && cargo test --lib

  test_imports:
    executor: rust
    environment:
      RUSTC_WRAPPER: oasis-build
    steps:
      - checkout
      - restore_oasis_build
      - run:
          name: Build dependency
          working_directory: tests/xcc-b
          command: cargo build --target wasm32-wasi --bins
      - run:
          name: Build toplevel
          working_directory: tests/xcc-a
          command: cargo build --target wasm32-wasi --bins && cargo test --lib

  docker_build:
    executor: docker_builder
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:pending .
          working_directory: .circleci/docker
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
      - docker_push:
          tag: pending

  update_linux_toolstate:
    executor: rust_pending
    steps:
      - update_toolstate
      - cache_oasis_build

  update_macos_toolstate:
    environment:
      PATH: /Users/distiller/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      LD_LIBRARY_PATH: /Users/distiller/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
    macos:
      xcode: "10.0.0"
    steps:
      - run:
          name: Install Rust
          command: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
      - run:
          name: Install AWS CLI
          command: pip install awscli
      - checkout
      - update_toolstate

  docker_publish:
    executor: docker_builder
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Tag image with latest
          command: docker tag $IMAGE_NAME:pending $IMAGE_NAME:latest
      - docker_push:
          tag: latest


workflows:
  version: 2

  test:
    jobs:
      - init
      - clippy
      - wasm_build
      - test_idl:
          requires:
            - init
      - test_imports:
          requires:
            - init
      - build_standalone_examples:
          requires:
            - init

  nightly:
    triggers:
      - schedule:
          cron: "0 14 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - docker_build
      - update_linux_toolstate:
          requires:
            - docker_build
      - update_macos_toolstate
      - docker_publish:
          requires:
            - update_linux_toolstate
