version: 2

jobs:
  init:
    docker:
      - image: nhdh/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - checkout
      - run:
          name: Checkstyle
          command: cargo fmt -- --check

  unit_test:
    docker:
      - image: nhdh/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - checkout
      - run:
          name: Unit tests
          command: cargo test --tests
          environment:
            SKIP_ABI_GEN: 1

  test_xcc:
    docker:
      - image: nhdh/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Cross-contract call integration test
          working_directory: tests/xcc-a
          command: cargo test --tests
          environment:
            SKIP_ABI_GEN: 1

  test_idl:
    docker:
      - image: nhdh/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Install idl-gen
          command: cargo install --path idl-gen
      - run:
          name: Test IDL generation
          working_directory: tests/idl_gen
          command: cargo test --tests

workflows:
  version: 2
  test:
    jobs:
      - init
      - unit_test:
          requires:
            - init
      - test_xcc:
          requires:
            - init
      - test_idl:
          requires:
            - init
