version: 2

jobs:
  init:
    docker:
      - image: oasislabs/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
    steps:
      - checkout
      - run:
          name: Rustfmt
          command: cargo fmt -- --check
      - run:
          name: Clippy
          command: cargo clippy -- -D clippy::all
      - run:
          name: Install mantle-build
          command: cargo install --path mantle-build
      - save_cache:
          key: mantle-build-{{ .Revision }}
          paths:
            - /root/.cargo/bin/mantle-build

  wasm_build:
    docker:
      - image: oasislabs/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Wasm build
          command: cargo build --target wasm32-unknown-unknown --all-features -p memchain -p bcfs

  unit_test:
    docker:
      - image: oasislabs/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
          MANTLE_BLOCKCHAIN_NAME: oasis
    steps:
      - checkout
      - restore_cache:
          keys:
            - mantle-build-{{ .Revision }}
      - run:
          name: Unit tests
          command: cargo test

  test_ballot_example:
    docker:
      - image: oasislabs/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
          MANTLE_BLOCKCHAIN_NAME: oasis
    resource_class: xlarge
    steps:
      - checkout
      - restore_cache:
          keys:
            - mantle-build-{{ .Revision }}
      - run:
          name: Build ballot example
          working_directory: examples/ballot
          command: cargo build --target wasm32-wasi
      - run:
          name: Test ballot example
          working_directory: examples/ballot
          command: cargo test

  test_messaging_example:
    docker:
      - image: oasislabs/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
          MANTLE_BLOCKCHAIN_NAME: oasis
    resource_class: xlarge
    steps:
      - checkout
      - restore_cache:
          keys:
            - mantle-build-{{ .Revision }}
      - run:
          name: Build messaging example
          working_directory: examples/messaging
          command: cargo build --target wasm32-wasi
      - run:
          name: Test messaging example
          working_directory: examples/messaging
          command: cargo test

  test_auctions_example:
    docker:
      - image: oasislabs/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
          MANTLE_BLOCKCHAIN_NAME: oasis
    resource_class: xlarge
    steps:
      - checkout
      - restore_cache:
          keys:
            - mantle-build-{{ .Revision }}
      - run:
          name: Build auctions example
          working_directory: examples/sealed-auctions
          command: cargo build --target wasm32-wasi
      - run:
          name: Test auctions example
          working_directory: examples/sealed-auctions
          command: cargo test
      - run:
          name: Test ERC20 example
          working_directory: examples/erc20
          command: cargo test --tests -- --test-threads 1
      - run:
          name: Test HelloWorld example
          working_directory: examples/hello-world
          command: cargo test

  test_idl:
    docker:
      - image: oasislabs/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
          MANTLE_BLOCKCHAIN_NAME: oasis
    resource_class: xlarge
    steps:
      - checkout
      - restore_cache:
          keys:
            - mantle-build-{{ .Revision }}
      - run:
          name: Test IDL generation
          working_directory: tests/idl-gen
          command: cargo build --target wasm32-wasi --bins && cargo test --lib

  test_imports:
    docker:
      - image: oasislabs/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
          MANTLE_BLOCKCHAIN_NAME: oasis
    resource_class: xlarge
    steps:
      - checkout
      - restore_cache:
          keys:
            - mantle-build-{{ .Revision }}
      - run:
          name: Build dependency
          working_directory: tests/xcc-b
          command: cargo build --target wasm32-wasi --bins
      - run:
          name: Build toplevel
          working_directory: tests/xcc-a
          command: cargo build --target wasm32-wasi --bins && cargo test --lib

workflows:
  version: 2
  test:
    jobs:
      - init
      - unit_test:
          requires:
            - init
      - wasm_build:
          requires:
            - init
      - test_idl:
          requires:
            - init
      - test_imports:
          requires:
            - init
      - test_ballot_example:
          requires:
            - init
      - test_messaging_example:
          requires:
            - init
      - test_auctions_example:
          requires:
            - init
