version: 2
jobs:
  build:
    docker:
      - image: nhdh/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          RUSTC_WRAPPER: sccache

    resource_class: xlarge

    steps:
      - run:
          name: Update Rust
          command: rustup update nightly

      - checkout

      - run:
          name: Checkstyle
          command: cargo fmt -- --check

      - run:
          name: Unit tests
          command: cargo test --tests
          environment:
            SKIP_ABI_GEN: 1

      - run:
          name: Cross-contract call integration test
          working_directory: tests/xcc-a
          command: cargo test --tests
          environment:
            SKIP_ABI_GEN: 1

      - run:
          name: Ballot ABI integration test
          working_directory: tests/ballot
          command: cargo test --tests
