version: 2.1


executors:
  rust:
    environment:
      PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
    docker:
      - image: oasislabs/rust:latest
    resource_class: xlarge

  rust_pending:
    environment:
      PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
    docker:
      - image: oasislabs/rust:pending
    resource_class: xlarge

  docker_builder:
    environment:
      IMAGE_NAME: oasislabs/rust
    docker:
      - image: circleci/buildpack-deps:bionic


commands:
  build_test_example:
    parameters:
      example:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - mantle-build-{{ .Revision }}
      - run:
          working_directory: examples/<< parameters.example >>
          command: cargo build --target wasm32-wasi
      - run:
          working_directory: examples/<< parameters.example >>
          command: cargo test

  docker_push:
    parameters:
      tag:
        type: string
    steps:
      - run:
          name: Push to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push oasislabs/rust:<< parameters.tag >>


jobs:
  init:
    executor: rust
    steps:
      - checkout
      - run:
          name: Rustfmt
          command: cargo fmt -- --check
      - run:
          name: Clippy
          command: cargo clippy --all-features -- -D clippy::all
      - run:
          name: Install mantle-build
          command: cargo install --path mantle-build
      - save_cache:
          key: mantle-build-{{ .Revision }}
          paths:
            - /root/.cargo/bin/mantle-build

  wasm_build:
    executor: rust
    steps:
      - checkout
      - run:
          name: Wasm build
          command: cargo build --target wasm32-unknown-unknown --all-features -p memchain -p bcfs

  unit_test:
    executor: rust
    steps:
      - checkout
      - restore_cache:
          keys:
            - mantle-build-{{ .Revision }}
      - run:
          name: Unit tests
          command: cargo test

  test_ballot_example:
    executor: rust
    steps:
      - build_test_example:
          example: ballot

  test_messaging_example:
    executor: rust
    steps:
      - build_test_example:
          example: messaging

  test_auctions_example:
    executor: rust
    steps:
      - build_test_example:
          example: sealed-auctions

  test_erc20_example:
    executor: rust
    steps:
      - build_test_example:
          example: erc20

  test_helloworld_example:
    executor: rust
    steps:
      - build_test_example:
          example: hello-world

  test_idl:
    executor: rust
    steps:
      - checkout
      - restore_cache:
          keys:
            - mantle-build-{{ .Revision }}
      - run:
          name: Test IDL generation
          working_directory: tests/idl-gen
          command: cargo build --target wasm32-wasi --bins && cargo test --lib

  test_imports:
    executor: rust
    steps:
      - checkout
      - restore_cache:
          keys:
            - mantle-build-{{ .Revision }}
      - run:
          name: Build dependency
          working_directory: tests/xcc-b
          command: cargo build --target wasm32-wasi --bins
      - run:
          name: Build toplevel
          working_directory: tests/xcc-a
          command: cargo build --target wasm32-wasi --bins && cargo test --lib

  docker_build:
    executor: docker_builder
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:pending .
          working_directory: .circleci/docker
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
      - docker_push:
          tag: pending

  update_toolstate:
    executor: rust_pending
    steps:
      - checkout
      - run:
          name: Build mantle-build
          command: cargo build --release -p mantle-build
      - run:
          name: Push to S3 bucket
          command: aws s3 cp target/release/mantle-build s3://mantle-framework/mantle-build

  docker_publish:
    executor: docker_builder
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Tag image with latest
          command: docker tag $IMAGE_NAME:pending $IMAGE_NAME:latest
      - docker_push:
          tag: latest


workflows:
  version: 2

  test:
    jobs:
      - init
      - unit_test:
          requires:
            - init
      - wasm_build:
          requires:
            - init
      - test_idl:
          requires:
            - init
      - test_imports:
          requires:
            - init
      - test_ballot_example:
          requires:
            - init
      - test_messaging_example:
          requires:
            - init
      - test_auctions_example:
          requires:
            - init
      - test_erc20_example:
          requires:
            - init
      - test_helloworld_example:
          requires:
            - init

  nightly:
    triggers:
      - schedule:
          cron: "0 14 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - docker_build
      - update_toolstate:
          requires:
            - docker_build
      - docker_publish:
          requires:
            - update_toolstate
