version: 2

jobs:
  init:
    docker:
      - image: nhdh/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - checkout
      - run:
          name: Checkstyle
          command: cargo fmt -- --check

  wasm_build:
    docker:
      - image: nhdh/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Wasm build
          command: cargo build --target wasm32-unknown-unknown --all-features -p memchain

  unit_test:
    docker:
      - image: nhdh/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - checkout
      - run:
          name: Unit tests
          command: cargo test --tests

  test_xcc:
    docker:
      - image: nhdh/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Cross-service call integration test
          working_directory: tests/xcc-a
          command: cargo test --tests

  test_examples:
    docker:
      - image: nhdh/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Test ballot example
          working_directory: examples/ballot
          command: cargo test --tests
      - run:
          name: Test messaging example
          working_directory: examples/messaging
          command: cargo test --tests

  test_idl:
    docker:
      - image: nhdh/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Install idl-gen
          command: cargo install --path idl-gen
      - run:
          name: Test IDL generation
          working_directory: tests/idl_gen
          command: cargo test --tests

workflows:
  version: 2
  test:
    jobs:
      - init
      - unit_test:
          requires:
            - init
      - test_xcc:
          requires:
            - init
      - test_idl:
          requires:
            - init
      - test_examples:
          requires:
            - init
      - wasm_build:
          requires:
            - init
