version: 2

jobs:
  init:
    docker:
      - image: nhdh/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
    steps:
      - checkout
      - run:
          name: Checkstyle
          command: cargo fmt -- --check

  wasm_build:
    docker:
      - image: nhdh/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Wasm build
          command: cargo build --target wasm32-unknown-unknown --all-features -p memchain -p bcfs

  unit_test:
    docker:
      - image: nhdh/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
    steps:
      - checkout
      - run:
          name: Install mantle-build
          command: cargo install --path mantle-build
      - run:
          name: Unit tests
          command: cargo test --tests

  test_examples:
    docker:
      - image: nhdh/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Install mantle-build
          command: cargo install --path mantle-build
      - run:
          name: Test ballot example
          working_directory: examples/ballot
          command: cargo test --tests
      - run:
          name: Test messaging example
          working_directory: examples/messaging
          command: cargo test --tests

  test_idl:
    docker:
      - image: nhdh/rust:latest
        environment:
          PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          LD_LIBRARY_PATH: /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Install mantle-build
          command: cargo install --path mantle-build
      - run:
          name: Test IDL generation
          working_directory: tests/idl_gen
          command: cargo test --tests --features mantle-build-test

workflows:
  version: 2
  test:
    jobs:
      - init
      - unit_test:
          requires:
            - init
      - test_idl:
          requires:
            - init
      - test_examples:
          requires:
            - init
      - wasm_build:
          requires:
            - init
