[package]
name = "bcfs"
version = "0.1.0"
authors = ["Oasis Labs <info@oasislabs.com>"]
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
hex = "0.3"
memchain = { version = "0.1", path = "../memchain", optional = true }
oasis-types = { version = "0.1", path = "../oasis-types" }
wasi-types = "0.1"

[features]
testing = ["memchain"]
