[package]
name = "oasis-types"
version = "0.1.0"
authors = ["Oasis Labs <info@oasislabs.com>"]
edition = "2018"

[dependencies]
blockchain-traits = { version = "0.1", path = "../blockchain-traits" }
hex = "0.3"
serde = { version = "1.0", features = ["derive"] }
