[package]
name = "oasis-std"
version = "0.1.0"
license = "Apache-2.0"
description = "A standard library for interacting with the Oasis platform."
edition = "2018"
repository = "https://github.com/oasislabs/oasis-rs.git"
authors = ["Oasis Labs <info@oasislabs.com>"]
readme = "README.md"
keywords = ["oasis", "owasm"]

[dependencies]
failure = "0.1"
fixed-hash = { version = "0.3", default-features = false }
oasis-macros = { version = "0.1", path = "../oasis-macros" }
serde = "1.0"
serde_cbor = "0.9"
serde_derive = "1.0"
uint = { version = "0.6", default-features = false }

[features]
platform-alloc = []
create2 = []
