[package]
name = "oasis-std"
version = "0.3.0"
license = "Apache-2.0"
description = "Library for developing on the Oasis platform"
edition = "2018"
repository = "https://github.com/oasislabs/oasis-rs"
authors = ["Oasis Labs <feedback@oasislabs.com>"]
readme = "README.md"
keywords = ["oasis"]

[dependencies]
blockchain-traits = { version = "0.2", path = "../blockchain-traits" }
borsh = "0.2"
cfg-if = "0.1"
oasis-macros = { version = "0.2", path = "../oasis-macros" }
oasis-types = { version = "0.2", path = "../oasis-types" }
thiserror = "1.0"
tiny-keccak = "1.4"

[dev-dependencies]
oasis-test = { version = "0.2", path = "../oasis-test" }
rand = "0.7"

[target.'cfg(target_os = "wasi")'.dependencies]
base64 = "0.11"
hex = "0.4"
wasi = "0.7"
