[package]
name = "oasis-std"
version = "0.1.0"
license = "Apache-2.0"
description = "A standard library for interacting with the Oasis platform."
edition = "2018"
repository = "https://github.com/oasislabs/oasis-rs.git"
authors = ["Oasis Labs <info@oasislabs.com>"]
readme = "README.md"
keywords = ["oasis", "owasm"]

[dependencies]
failure = "0.1"
fixed-hash = { version = "0.3", default-features = false, features = ["byteorder"] }
oasis-macros = { version = "0.1", path = "../oasis-macros" }
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.9"
uint = "0.6"

[dev-dependencies]
oasis-test = { path = "../oasis-test" }
serde = { version = "1.0", features = ["derive"] }

[features]
platform-alloc = []
create2 = []
