[package]
name = "memchain"
version = "0.1.0"
authors = ["Oasis Labs <info@oasislabs.com>"]
edition = "2018"

[lib]
crate_type = ["rlib", "cdylib"]

[dependencies]
blockchain-traits = { version = "0.1", path = "../blockchain-traits" }
oasis-types = { version = "0.1", path = "../oasis-types" }
