[package]
name = "ballot"
version = "0.1.0"
authors = ["Oasis Labs <info@oasislabs.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
mantle = { git = "https://github.com/oasislabs/mantle" }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
mantle-test = { git = "https://github.com/oasislabs/mantle" } # required for tests

[build-dependencies]
mantle = { git = "https://github.com/oasislabs/mantle" } # required for build script

[features]
deploy = [] # (automatically) set when building deployable service Wasm binary
